services:
  db:
    container_name: tabbycat-db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=tabbycat
      - POSTGRES_USER=tabbycat
      - POSTGRES_DB=tabbycat
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      home:
        ipv4_address: 172.25.0.9

  redis:
    container_name: tabbycat-redis
    image: redis:6
    volumes:
     - ./data/redis:/data
    networks:
      home:
        ipv4_address: 172.25.0.10

  web:
    container_name: tabbycat-web
    build: .
    # Hack to wait until Postgres is up before running things
    command: ["./bin/docker-wait.sh", "--timeout=0", "db:5432", "--", "./bin/docker-run-honcho.sh"]
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - IN_DOCKER=1
      - DISABLE_SENTRY=1
      - DOCKER_REDIS=1
      - USING_NGINX=1
    working_dir: /tcd
    networks:
      home:
        ipv4_address: 172.25.0.8

  worker:
    container_name: tabbycat-worker
    build: .
    # Hack to wait until migration is done before running things
    command: ["./bin/docker-wait.sh", "--timeout=0", "web:8000", "--", "./bin/docker-run-worker.sh"]
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - IN_DOCKER=1
      - DISABLE_SENTRY=1
      - DOCKER_REDIS=1
      - USING_NGINX=1
    working_dir: /tcd
    networks:
      home:
        ipv4_address: 172.25.0.11

networks:
  home:
    external: true
    name: home